### ISSUE TITLE
node_sleep.node: undefined symbol

### ISSUE THREAD

**Issue by robbieb43** [Jalle19/node-ffmpeg-mpegts-proxy#37]
Hi 

Using node.js v8.0.0, installed using nvm.  Also tried previously other installs (subsequently cleaned from system) and similar error occurs.

When I run I get:

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/pi/projects/ffmpeg-tsmpeg-proxy/node-ffmpeg-mpegts-proxy/node_modules/sleep/build/Release/node_sleep.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/projects/ffmpeg-tsmpeg-proxy/node-ffmpeg-mpegts-proxy/node_modules/sleep/index.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

The module appears present but I am a node.js beginner.

Thanks

Rob

**Comment by Jalle19** [comment]
Are you sure you don't have any other NodeJS installations lingering on your system? From what I can tell this error mostly happens when you somehow have more than one version installed.

**Comment by robbieb43** [comment]
Thanks - despite following several FAQs on complete removal I still had an old binary as well as the nvm installed version.  Propose to close this.
