### ISSUE TITLE
Error on Synology DS918+

### ISSUE THREAD

**Issue by findingneo17** [Jalle19/node-ffmpeg-mpegts-proxy#48]
Seems I have an similar issue running on Synology DS918+ where I'm getting an error from node.js. New to node so would appreciate any pointers.

hts@Diskstation:~$ node -v
v8.9.4
hts@Diskstation:~$ node ~/tvh/node-ffmpeg-mpegts-proxy/node-ffmpeg-mpegts-proxy.js -l 192.168.1.238 -p 9128 -a ffmpeg -s ~/tvh/hts.channels.json
module.js:540
throw err;
^
Error: Cannot find module './build/Release/node_sleep.node'
at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Module.require (module.js:587:17)
at require (internal/module.js:11:18)
at Object. (/volume1/git/node-ffmpeg-mpegts-proxy/node_modules/sleep/index.js:2:18)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)

Am trying to follow instructions from here:
http://jafath.blogspot.com/2017/11/tvheadend-for-users-in-us-part-2.html

Following seems to have worked:
sudo apt install build-essential libav-tools
cd ~/tvh
git clone https://github.com/Jalle19/node-ffmpeg-mpegts-proxy
cd ~/tvh/node-ffmpeg-mpegts-proxy
npm install

But then running the above node command gives me an error about module node_sleep.node wasn't found.

Many thanks in advance!

**Comment by Jalle19** [comment]
Your installation is most likely screwed up somehow, can you try https://github.com/nwjs/nw.js/issues/5538#issuecomment-265986507 ?
